[project]
name = "comfyui_if_trellis"
description = "ComfyUI TRELLIS generates 3D modelsfrom pictures"
version = "0.0.1"
license = { file = "LICENSE.txt" } 
dependencies = [
  "pillow", 
  "imageio",
  "imageio-ffmpeg",
  "tqdm", 
  "easydict",
  "opencv-python-headless",
  "rembg",
  "onnxruntime-gpu",
  "scipy",
  "ninja",
  "plyfile",
  "diso",
  "trimesh",
  "xatlas",
  "pyvista",
  "pymeshfix",
  "igraph",
  "utils3d",
  "spconv-cu124",
]


[project.urls]
Repository = "https://github.com/if-ai/ComfyUI-IF_Trellis"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "impactframes"
DisplayName = "ComfyUI-IF_Trellis"
Icon = ""
